# Shared readers for the project anatomy registry, the prepared Heiss table,
# and comparison-specific anatomical crosswalks. Persistent mapping decisions
# are keyed by stable anatomy_id values. join_heiss_rates() is the single
# compatibility boundary for summaries that currently retain only a label.

.require_columns <- function(data, columns, object_name) {
  missing <- setdiff(columns, names(data))
  if (length(missing)) {
    stop(
      object_name, " is missing required column(s): ",
      paste(missing, collapse = ", "),
      call. = FALSE
    )
  }
}

.assert_unique <- function(x, label) {
  x <- trimws(as.character(x))
  if (anyNA(x) || any(x == "")) {
    stop(label, " contains missing or blank values.", call. = FALSE)
  }
  duplicates <- unique(x[duplicated(x)])
  if (length(duplicates)) {
    stop(
      label, " contains duplicate value(s): ",
      paste(duplicates, collapse = ", "),
      call. = FALSE
    )
  }
}

read_anatomy_registry <- function(
  path = "metadata/anatomy/anatomy_registry.csv"
) {
  if (!file.exists(path)) {
    stop("Anatomy registry not found: ", path, call. = FALSE)
  }
  registry <- read.csv(path, stringsAsFactors = FALSE, check.names = FALSE)
  .require_columns(
    registry,
    c("anatomy_id", "canonical_label", "color_hex", "display_order"),
    path
  )
  .assert_unique(registry$anatomy_id, paste0(path, "$anatomy_id"))
  registry
}

# Read the source-independent preparation regenerated by
# scripts/00_prepare_heiss_rates.R. The raw Heiss Table 1 remains authoritative.
read_heiss_regions <- function(
  path = "data_intermediate/heiss_2004_regions.csv",
  include_global_average = TRUE
) {
  if (!file.exists(path)) {
    stop(
      "Prepared Heiss data not found: ", path,
      ". Run scripts/00_prepare_heiss_rates.R first.",
      call. = FALSE
    )
  }

  heiss <- read.csv(path, stringsAsFactors = FALSE, check.names = FALSE)
  .require_columns(
    heiss,
    c(
      "heiss_region", "anatomy_id", "canonical_label",
      "rcmrglc_mean_umol_100g_min", "rcmrglc_sd_umol_100g_min"
    ),
    path
  )
  .assert_unique(heiss$heiss_region, paste0(path, "$heiss_region"))
  .assert_unique(heiss$anatomy_id, paste0(path, "$anatomy_id"))

  if (!include_global_average) {
    heiss <- heiss[
      !grepl("average", tolower(heiss$heiss_region), fixed = TRUE),
      , drop = FALSE
    ]
  }
  rownames(heiss) <- NULL
  heiss
}

# Backwards-compatible compact view used by the s1b analyses. anatomy_id is
# deliberately retained so new code can join by ID rather than rcmr_term.
read_heiss_rcmr <- function(
  path = "data_intermediate/heiss_2004_regions.csv",
  include_global_average = FALSE
) {
  heiss <- read_heiss_regions(path, include_global_average)
  out <- data.frame(
    anatomy_id = heiss$anatomy_id,
    rcmr_term = trimws(as.character(heiss$heiss_region)),
    rcmr_value = round(as.numeric(heiss$rcmrglc_mean_umol_100g_min), 1),
    stringsAsFactors = FALSE
  )
  keep <- !is.na(out$anatomy_id) & out$anatomy_id != "" &
    !is.na(out$rcmr_term) & out$rcmr_term != "" &
    !is.na(out$rcmr_value)
  out <- out[keep, , drop = FALSE]
  .assert_unique(out$anatomy_id, "prepared Heiss anatomy_id")
  rownames(out) <- NULL
  out
}

# All comparison-specific maps use the same schema. Multiple rows for one
# source region are allowed when the rate is an explicit composite (s2) or a
# source parcel is divided between target regions (s4a).
read_study_anatomy_map <- function(path) {
  if (!file.exists(path)) {
    stop("Study anatomy map not found: ", path, call. = FALSE)
  }
  mapping <- read.csv(
    path,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    na.strings = c("", "NA")
  )
  .require_columns(
    mapping,
    c(
      "source_region", "analysis_anatomy_id", "heiss_anatomy_id",
      "component_weight", "relationship", "mapping_note"
    ),
    path
  )

  mapping$source_region <- trimws(mapping$source_region)
  mapping$analysis_anatomy_id <- trimws(mapping$analysis_anatomy_id)
  mapping$heiss_anatomy_id <- trimws(mapping$heiss_anatomy_id)
  mapping$component_weight <- as.numeric(mapping$component_weight)
  required_text <- c(
    "source_region", "analysis_anatomy_id", "relationship", "mapping_note"
  )
  for (column in required_text) {
    if (anyNA(mapping[[column]]) || any(trimws(mapping[[column]]) == "")) {
      stop(path, "$", column, " contains missing or blank values.",
           call. = FALSE)
    }
  }
  .assert_unique(
    paste(
      mapping$source_region,
      mapping$analysis_anatomy_id,
      ifelse(is.na(mapping$heiss_anatomy_id), "", mapping$heiss_anatomy_id),
      sep = " :: "
    ),
    paste0(path, " source/analysis/Heiss mapping rows")
  )

  registry <- read_anatomy_registry()
  unknown_analysis_ids <- setdiff(
    unique(mapping$analysis_anatomy_id), registry$anatomy_id
  )
  if (length(unknown_analysis_ids)) {
    stop(
      path, " uses analysis_anatomy_id value(s) absent from the registry: ",
      paste(unknown_analysis_ids, collapse = ", "),
      call. = FALSE
    )
  }

  heiss <- read_heiss_regions()
  mapped_heiss_ids <- unique(mapping$heiss_anatomy_id)
  mapped_heiss_ids <- mapped_heiss_ids[!is.na(mapped_heiss_ids)]
  unknown_heiss_ids <- setdiff(mapped_heiss_ids, heiss$anatomy_id)
  if (length(unknown_heiss_ids)) {
    stop(
      path, " uses heiss_anatomy_id value(s) absent from prepared Heiss data: ",
      paste(unknown_heiss_ids, collapse = ", "),
      call. = FALSE
    )
  }

  has_heiss <- !is.na(mapping$heiss_anatomy_id)
  if (any(has_heiss &
          (is.na(mapping$component_weight) | mapping$component_weight <= 0))) {
    stop(
      path, " must give every Heiss component a positive component_weight.",
      call. = FALSE
    )
  }
  if (any(!has_heiss & !is.na(mapping$component_weight))) {
    stop(
      path, " has a component_weight on a row without a Heiss component.",
      call. = FALSE
    )
  }
  mapping
}

# Resolve a comparison map to one rate per source-region/analysis-ID pair.
# Component weights are normalized within each pair. A single direct target is
# displayed with its native Heiss label; composites use the registry label.
derive_study_heiss_rates <- function(mapping_or_path) {
  mapping <- if (is.character(mapping_or_path) && length(mapping_or_path) == 1L) {
    read_study_anatomy_map(mapping_or_path)
  } else {
    mapping_or_path
  }
  .require_columns(
    mapping,
    c(
      "source_region", "analysis_anatomy_id", "heiss_anatomy_id",
      "component_weight"
    ),
    "study anatomy mapping"
  )

  heiss <- read_heiss_regions()
  registry <- read_anatomy_registry()
  pair_key <- paste(
    mapping$source_region, mapping$analysis_anatomy_id, sep = "\r"
  )
  pair_levels <- unique(pair_key)

  resolved <- lapply(pair_levels, function(key) {
    rows <- mapping[pair_key == key, , drop = FALSE]
    rate_rows <- rows[!is.na(rows$heiss_anatomy_id), , drop = FALSE]
    analysis_id <- rows$analysis_anatomy_id[1]
    canonical_label <- registry$canonical_label[
      match(analysis_id, registry$anatomy_id)
    ]

    if (!nrow(rate_rows)) {
      return(data.frame(
        source_region = rows$source_region[1],
        anatomy_id = analysis_id,
        anatomy_group = canonical_label,
        rcmr_value = NA_real_,
        rcmr_sd = NA_real_,
        n_heiss_components = 0L,
        stringsAsFactors = FALSE
      ))
    }

    idx <- match(rate_rows$heiss_anatomy_id, heiss$anatomy_id)
    weights <- rate_rows$component_weight / sum(rate_rows$component_weight)
    direct <- nrow(rate_rows) == 1L &&
      analysis_id == rate_rows$heiss_anatomy_id[1]
    display_label <- if (direct) heiss$heiss_region[idx] else canonical_label
    resolved_sd <- if (nrow(rate_rows) == 1L) {
      heiss$rcmrglc_sd_umol_100g_min[idx]
    } else {
      # Components were measured in the same participants and are not
      # independent; without their covariance, a composite SD is undefined.
      NA_real_
    }

    data.frame(
      source_region = rows$source_region[1],
      anatomy_id = analysis_id,
      anatomy_group = display_label,
      rcmr_value = round(sum(
        heiss$rcmrglc_mean_umol_100g_min[idx] * weights
      ), 1),
      rcmr_sd = resolved_sd,
      n_heiss_components = nrow(rate_rows),
      stringsAsFactors = FALSE
    )
  })

  out <- do.call(rbind, resolved)
  rownames(out) <- NULL
  out
}

read_s1b_roi_map <- function(
  path = "metadata/anatomy/s1b_linnarsson_roi_map.csv"
) {
  mapping <- read_study_anatomy_map(path)
  .require_columns(
    mapping,
    c("is_cerebral_cortex", "is_neocortex", "is_telencephalon"),
    path
  )

  for (column in c(
    "is_cerebral_cortex", "is_neocortex", "is_telencephalon"
  )) {
    value <- toupper(trimws(as.character(mapping[[column]])))
    if (anyNA(value) || any(!value %in% c("TRUE", "FALSE"))) {
      stop(
        path, "$", column, " must contain only TRUE or FALSE.",
        call. = FALSE
      )
    }
    mapping[[column]] <- value == "TRUE"
  }
  if (any(mapping$is_neocortex & !mapping$is_cerebral_cortex)) {
    stop(
      path, " cannot classify an ROI as neocortex without also classifying ",
      "it as cerebral cortex.",
      call. = FALSE
    )
  }
  if (any(mapping$is_cerebral_cortex & !mapping$is_telencephalon)) {
    stop(
      path, " cannot classify an ROI as cerebral cortex without also ",
      "classifying it as telencephalon.",
      call. = FALSE
    )
  }

  scope_rows <- unique(mapping[c(
    "analysis_anatomy_id", "is_cerebral_cortex", "is_neocortex",
    "is_telencephalon"
  )])
  inconsistent_ids <- unique(
    scope_rows$analysis_anatomy_id[
      duplicated(scope_rows$analysis_anatomy_id) |
        duplicated(scope_rows$analysis_anatomy_id, fromLast = TRUE)
    ]
  )
  if (length(inconsistent_ids)) {
    stop(
      path, " gives inconsistent scope flags within analysis anatomy ID(s): ",
      paste(inconsistent_ids, collapse = ", "),
      call. = FALSE
    )
  }

  .assert_unique(mapping$source_region, paste0(path, "$source_region"))
  resolved <- derive_study_heiss_rates(mapping)
  idx <- match(resolved$source_region, mapping$source_region)
  resolved$is_cerebral_cortex <- mapping$is_cerebral_cortex[idx]
  resolved$is_neocortex <- mapping$is_neocortex[idx]
  resolved$is_telencephalon <- mapping$is_telencephalon[idx]
  names(resolved)[names(resolved) == "source_region"] <- "roi"
  resolved
}

attach_s1b_anatomy <- function(data, roi_col = "roi",
                               unmapped_label = "Unmapped") {
  if (!roi_col %in% names(data)) {
    stop("Input data has no ROI column named ", roi_col, ".", call. = FALSE)
  }
  mapping <- read_s1b_roi_map()
  roi <- trimws(as.character(data[[roi_col]]))
  idx <- match(roi, mapping$roi)
  data[[roi_col]] <- roi
  data$anatomy_id <- mapping$anatomy_id[idx]
  data$anatomy_group <- mapping$anatomy_group[idx]
  data$is_cerebral_cortex <- mapping$is_cerebral_cortex[idx]
  data$is_neocortex <- mapping$is_neocortex[idx]
  data$is_telencephalon <- mapping$is_telencephalon[idx]
  data$anatomy_group[is.na(data$anatomy_group)] <- unmapped_label
  data
}

# Compatibility join for analysis summaries that currently retain only their
# Heiss display label after aggregation. ID resolution happens here, once,
# against the central prepared table; the returned data carry anatomy_id.
join_heiss_rates <- function(data, label_col = "anatomy_group",
                             include_global_average = FALSE) {
  if (!label_col %in% names(data)) {
    stop("Input data has no anatomy label column named ", label_col, ".",
         call. = FALSE)
  }
  rates <- read_heiss_rcmr(
    include_global_average = include_global_average
  )
  idx <- match(trimws(as.character(data[[label_col]])), rates$rcmr_term)
  keep <- !is.na(idx)
  out <- data[keep, , drop = FALSE]
  out$anatomy_id <- rates$anatomy_id[idx[keep]]
  out$rcmr_value <- rates$rcmr_value[idx[keep]]
  out
}
