# Read the source-independent Heiss preparation used by studies 1 and 2.
# The preparation is regenerated by scripts/00_prepare_heiss_rates.R from the
# raw Heiss table plus the project anatomy registry and Heiss source map.
read_heiss_rcmr <- function(
  path = "data_intermediate/heiss_2004_regions.csv",
  include_global_average = FALSE
) {
  if (!file.exists(path)) {
    stop(
      "Prepared Heiss data not found: ", path,
      ". Run scripts/00_prepare_heiss_rates.R first.",
      call. = FALSE
    )
  }

  heiss <- read.csv(path, stringsAsFactors = FALSE, check.names = FALSE)
  required <- c("heiss_region", "rcmrglc_mean_umol_100g_min")
  missing <- setdiff(required, names(heiss))
  if (length(missing)) {
    stop(
      path, " is missing required column(s): ",
      paste(missing, collapse = ", "),
      call. = FALSE
    )
  }

  out <- data.frame(
    rcmr_term = trimws(as.character(heiss$heiss_region)),
    rcmr_value = round(as.numeric(heiss$rcmrglc_mean_umol_100g_min), 1),
    stringsAsFactors = FALSE
  )
  keep <- !is.na(out$rcmr_term) & out$rcmr_term != "" &
    !is.na(out$rcmr_value)
  if (!include_global_average) {
    keep <- keep & !grepl("average", tolower(out$rcmr_term), fixed = TRUE)
  }
  out <- out[keep, , drop = FALSE]

  duplicate_terms <- unique(out$rcmr_term[duplicated(out$rcmr_term)])
  if (length(duplicate_terms)) {
    stop(
      "Prepared Heiss data contains duplicate region term(s): ",
      paste(duplicate_terms, collapse = ", "),
      call. = FALSE
    )
  }

  rownames(out) <- NULL
  out
}
